name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11' # Specify your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine # Explicitly install Twine for clarity

    - name: Build package
      run: python -m build

    - name: Verify package with Twine
      run: twine check dist/* # This step will check your package for common issues

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2 # Use a tagged version for better stability
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
